title: '本课题组隶属于东南大学自动化学院' # title in broswer
publicPath: '/'
resumePath: './README.md'
showHeader: true
headerInfo:
  # photo: 'https://avatars1.githubusercontent.com/u/22113206?s=460&v=4'
  photo: './markdown/avatar.jpeg'
  name: 'bigLiao'
  phone: '151****1111'
  email: 'bigliao@markcv.com'
